import RootLayout from '@/components/RootLayout';
import { AuthProvider } from '@/context/Auth';
import { MantineProvider } from '@mantine/core';
import { Hydrate, QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { AppProps } from 'next/app';
import { Tajawal } from 'next/font/google';
import Head from 'next/head';
import React from 'react';
import '../styles/globals.css';
const tajawal = Tajawal({
  subsets: ['arabic'],
  weight: ['200', '300', '400', '500', '700', '800', '900'],
});

export default function App(props: AppProps) {
  const { Component, pageProps } = props;
  const [queryClient] = React.useState(() => new QueryClient());
  return (
    <>
      <Head>
        <title>First Trade Union</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MantineProvider
        withGlobalStyles
        withNormalizeCSS
        theme={{
          /** Put your mantine theme override here */
          colorScheme: 'light',
          ...tajawal.style,
        }}
      >
        <QueryClientProvider client={queryClient}>
          <Hydrate state={pageProps.dehydratedState}>
            <AuthProvider>
              <RootLayout>
                <Component {...pageProps} />
              </RootLayout>
            </AuthProvider>
          </Hydrate>
        </QueryClientProvider>
      </MantineProvider>
    </>
  );
}
